server:
  port: 7000

spring:
  application:
    name: blog-user
  datasource:
    url: jdbc:mysql://localhost:3306/blog-system?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10s

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


sa-token:
  token-name: blog-system-token
  timeout: 3000
  activity-timeout: 1800
  is-concurrent: true
  is-share: true
  is-log: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
    register-with-eureka: true
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: blog
