server:
  port: 7002
spring:
  application:
    name: blog-eureka
eureka:
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false